from __future__ import unicode_literals

import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path

CONFIG_DIR_NAME = ".migradiff"
CONFIG_FILE_NAME = "config.json"
DEFAULT_MODEL = "claude-haiku-4-5-20251001"
MAX_TOKENS = 1024
TEMPERATURE = 0

SYSTEM_PROMPT = (
    "You are a PostgreSQL database migration expert. You will be given"
    " a SQL migration script generated by MigraDiff. Explain what the"
    " migration does in plain English, identify any risks, and suggest"
    " safer alternatives for destructive operations. Be concise and"
    " practical. Format your response with numbered points for each"
    " statement. End with an overall risk assessment: LOW, MEDIUM, or HIGH."
)


def _config_dir():
    return Path.home() / CONFIG_DIR_NAME


def _config_path():
    return _config_dir() / CONFIG_FILE_NAME


def redact_api_key(text):
    return re.sub(r"sk-ant-[a-zA-Z0-9-]+", "sk-ant-***", text)


def resolve_api_key(cli_key=None):
    if cli_key:
        return cli_key
    env_key = os.environ.get("ANTHROPIC_API_KEY")
    if env_key:
        return env_key
    cfg = load_config()
    if cfg and "anthropic_api_key" in cfg:
        return cfg["anthropic_api_key"]
    return None


def load_config():
    path = _config_path()
    if path.exists():
        with open(path, "r") as f:
            return json.load(f)
    return None


def save_config(config):
    d = _config_dir()
    d.mkdir(mode=0o700, parents=True, exist_ok=True)
    path = _config_path()
    with open(path, "w") as f:
        json.dump(config, f, indent=2)
    path.chmod(0o600)


def validate_api_key(key):
    try:
        import anthropic

        client = anthropic.Anthropic(api_key=key)
        client.messages.create(
            model=DEFAULT_MODEL,
            max_tokens=10,
            messages=[{"role": "user", "content": "ping"}],
        )
        return True
    except anthropic.APIStatusError as e:
        msg = str(e)
        if "invalid" in msg.lower() or "401" in msg or "403" in msg:
            raise ValueError("Invalid API key")
        raise
    except ImportError:
        raise


def build_explain_prompt(sql_statements, timestamp, count, has_destructive):
    dest_str = "yes" if has_destructive else "no"
    user_prompt = (
        "Migration script to explain:\n\n"
        "{sql_statements}\n\n"
        "Database context:\n"
        "- Tool: MigraDiff (PostgreSQL schema diff)\n"
        "- Generated at: {timestamp}\n"
        "- Statements: {count}\n"
        "- Destructive operations detected: {dest_str}\n\n"
        "Explain each statement, identify risks, and suggest safer"
        " alternatives where applicable."
    )
    return user_prompt.format(
        sql_statements=sql_statements,
        timestamp=timestamp,
        count=count,
        dest_str=dest_str,
    )


class AIExplainer:
    def __init__(self, api_key):
        self.api_key = api_key

    def explain(self, sql_statements, statements_info):
        import anthropic

        has_destructive = any(s.get("risk") == "destructive" for s in statements_info)
        count = len(statements_info)
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

        user_prompt = build_explain_prompt(
            sql_statements, timestamp, count, has_destructive
        )

        client = anthropic.Anthropic(api_key=self.api_key)
        try:
            response = client.messages.create(
                model=DEFAULT_MODEL,
                max_tokens=MAX_TOKENS,
                temperature=TEMPERATURE,
                system=SYSTEM_PROMPT,
                messages=[{"role": "user", "content": user_prompt}],
            )
            text = response.content[0].text
            return {
                "text": text,
                "model": DEFAULT_MODEL,
                "generated_at": timestamp,
            }
        except Exception as e:
            msg = redact_api_key(str(e))
            raise RuntimeError("MigraDiff: AI explanation failed: {}".format(msg))


def setup_ai_interactive(out, err):
    key = None
    try:
        import anthropic
    except ImportError:
        print(
            "MigraDiff: --setup-ai requires the AI extras.",
            file=err,
        )
        print("Install with: pip install migradiff[ai]", file=err)
        return 1

    print("MigraDiff AI Setup", file=out)
    print("==================", file=out)

    import getpass

    raw_key = getpass.getpass("Enter your Anthropic API key (input hidden): ")
    key = raw_key.strip()

    print("Validating key...", file=out)

    try:
        validate_api_key(key)
    except ValueError as e:
        print("{}".format(e), file=err)
        print(
            "Please check your key at https://console.anthropic.com",
            file=err,
        )
        return 1
    except anthropic.APIStatusError as e:
        msg = redact_api_key(str(e))
        print("Key validation failed: {}".format(msg), file=err)
        return 1
    except Exception as e:
        msg = redact_api_key(str(e))
        print("Key validation failed: {}".format(msg), file=err)
        return 1

    existing = load_config() or {}
    existing["anthropic_api_key"] = key
    existing.setdefault("ai_model", DEFAULT_MODEL)
    existing.setdefault("explain_verbosity", "standard")

    try:
        save_config(existing)
    except Exception as e:
        print("Failed to save config: {}".format(e), file=err)
        return 1

    print("Key validated successfully.", file=out)
    from pathlib import Path

    config_path = Path.home() / CONFIG_DIR_NAME / CONFIG_FILE_NAME
    print(
        "Saved to {} (chmod 600)".format(config_path),
        file=out,
    )
    print(file=out)
    print("You can now use --explain with any diff command.", file=out)
    print(
        "Run: migra --explain postgres://db_a postgres://db_b",
        file=out,
    )
    return 0
